steps:
- checkout: self
  clean: true
  fetchDepth: 5

- script: sudo ./.azure-pipelines/posix-deps-yum.sh
  displayName: 'Install dependencies'

- script: ./configure  --enable-shared --enable-optimizations --with-pymalloc --without-doc-strings --prefix=$(Build.ArtifactStagingDirectory)
  displayName: 'Configure CPython'

- template: ./unix-make-publish.yml
  parameters:
    artifactName: python_centos_74
