variables:
  - name: ldflags
    value: '-Wl,-rpath=\$$ORIGIN/../lib' 

steps:
- checkout: self
  clean: true
  fetchDepth: 5

- script: ./configure --enable-shared --enable-optimizations --with-pymalloc --without-doc-strings --prefix=$(Build.ArtifactStagingDirectory)
  displayName: 'Configure CPython'

- template: ./unix-make-publish.yml
  parameters:
    artifactName: python_centos_74
