variables:
  coverage: false

trigger: ['master', '3.9', '3.8', '3.7']

jobs:
- job: Prebuild
  displayName: Pre-build checks

  pool:
    vmImage: ubuntu-18.04

  steps:
  - template: ./prebuild-checks.yml


- job: macOS_Build
  displayName: macOS Build
  dependsOn: Prebuild
  condition: and(succeeded(), eq(dependencies.Prebuild.outputs['tests.run'], 'true'))

  pool:
    vmImage: macos-10.14

  steps:
  - template: ./macos-steps.yml


- job: Ubuntu_Build
  displayName: Ubuntu Build
  dependsOn: Prebuild
  condition: and(succeeded(), eq(dependencies.Prebuild.outputs['tests.run'], 'true'))

  pool:
    vmImage: ubuntu-18.04

  steps:
  - template: ./ubuntu-steps.yml


- job: CentOS_Build
  displayName: CentOS Build
  dependsOn: Prebuild
  condition: and(succeeded(), eq(dependencies.Prebuild.outputs['tests.run'], 'true'))

  pool:
    vmImage: 'ubuntu-18.04'
  container: helloadam/hobbitscentosbuilder:latest

  steps:
    - template: ./centos-steps.yml


- job: Windows_Build
  displayName: Windows Build
  dependsOn: Prebuild
  condition: and(succeeded(), eq(dependencies.Prebuild.outputs['tests.run'], 'true'))

  pool:
    vmImage: windows-2019

  steps:
  - template: ./windows-steps.yml
