variables:
  coverage: false

trigger: ['master', '3.9', '3.8', '3.7']

jobs:
- job: Prebuild
  displayName: Pre-build checks

  pool:
    vmImage: ubuntu-18.04

  steps:
  - template: ./prebuild-checks.yml


- job: macOS_Build
  displayName: macOS Build
  dependsOn: Prebuild
  condition: and(succeeded(), eq(dependencies.Prebuild.outputs['tests.run'], 'true'))

  variables:
    testRunTitle: '$(build.sourceBranchName)-macos'
    testRunPlatform: macos

  pool:
    vmImage: macos-10.14

  steps:
  - template: ./macos-steps.yml


- job: Ubuntu_Build
  displayName: Ubuntu Build
  dependsOn: Prebuild
  condition: and(succeeded(), eq(dependencies.Prebuild.outputs['tests.run'], 'true'))

  pool:
    vmImage: ubuntu-18.04

  variables:
    testRunTitle: '$(build.sourceBranchName)-linux'
    testRunPlatform: linux
    openssl_version: 1.1.1g

  steps:
  - template: ./posix-steps.yml
    parameters:
      dependencies: apt


- job: Windows_Build
  displayName: Windows Build
  dependsOn: Prebuild
  condition: and(succeeded(), eq(dependencies.Prebuild.outputs['tests.run'], 'true'))

  pool:
    vmImage: windows-2019

  variables:
    arch: amd64
    testRunTitle: '$(Build.SourceBranchName)-win64'
    testRunPlatform: win64

  steps:
  - template: ./windows-steps.yml
