parameters:
  buildDir: $(Build.ArtifactStagingDirectory)
  linkFix: false


steps:
  - script: |
      rm -rf ${{ parameters.buildDir }}/share
      rm -rf ${{ parameters.buildDir }}/bin/2to3*
      rm -rf ${{ parameters.buildDir }}/bin/idle3*
      rm -rf ${{ parameters.buildDir }}/lib/python3.8/config-3.8-*
      rm -rf ${{ parameters.buildDir }}/lib/python3.8/idlelib
      rm -rf ${{ parameters.buildDir }}/lib/python3.8/lib2to3
      rm -rf ${{ parameters.buildDir }}/lib/python3.8/pydoc_data
      rm -rf ${{ parameters.buildDir }}/lib/python3.8/idlelib
      rm -rf ${{ parameters.buildDir }}/lib/python3.8/test
      rm -rf ${{ parameters.buildDir }}/lib/python3.8/tkinter
    displayName: 'Clean up installation'

  - script: |
      rm -f ${{ parameters.buildDir }}/lib/libpython3.8.so
      ln -s ${{ parameters.buildDir }}/lib/libpython3.8.so.1.0 ${{ parameters.buildDir }}/lib/libpython3.8.so
    condition: and(succeeded(), eq('${{ parameters.linkFix }}', true))