steps:
- checkout: self
  clean: true
  fetchDepth: 5

- script: ./configure --enable-framework --with-pymalloc --without-doc-strings --with-openssl=/usr/local/opt/openssl --prefix=$(Build.ArtifactStagingDirectory)
  displayName: 'Configure CPython'

- script: make -j4
  displayName: 'Build CPython'

- script: make pythoninfo
  displayName: 'Display build info'

- script: make install
  displayName: 'Install into staging directory'

- template: ./clean-up-build.yml
  parameters:
    buildDir: $(Build.ArtifactStagingDirectory)
  displayName: 'Clean up installation'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: python_macos_1014