steps:
- checkout: self
  clean: true
  fetchDepth: 5

- script: ./configure --enable-optimizations --enable-shared --with-pymalloc --with-openssl=/usr/local/opt/openssl --prefix=$(Build.ArtifactStagingDirectory)
  displayName: 'Configure CPython'

- script: make -j4
  displayName: 'Build CPython'

- script: make pythoninfo
  displayName: 'Display build info'

- script: make install
  displayName: 'Install into staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: python_macos_1014