
steps:
- checkout: self
  clean: true
  fetchDepth: 5

# Work around a known issue affecting Ubuntu VMs on Pipelines
- script: sudo setfacl -Rb /home/vsts
  displayName: 'Workaround ACL issue'

- script: sudo ./.azure-pipelines/posix-deps-apt.sh
  displayName: 'Install dependencies'

- script: ./configure  --enable-shared --with-pymalloc --without-doc-strings --prefix=$(Build.ArtifactStagingDirectory)
  displayName: 'Configure CPython'

- script: make -j4
  displayName: 'Build CPython'

- script: make pythoninfo
  displayName: 'Display build info'

- script: make install
  displayName: 'Install into staging directory'

- script: |
    rm -rf $(Build.ArtifactStagingDirectory)/lib/python3.8/config-3.8-*
    rm -rf $(Build.ArtifactStagingDirectory)/lib/python3.8/idlelib
    rm -rf $(Build.ArtifactStagingDirectory)/lib/python3.8/lib2to3
    rm -rf $(Build.ArtifactStagingDirectory)/lib/python3.8/pydoc_data
    rm -rf $(Build.ArtifactStagingDirectory)/lib/python3.8/idlelib
    rm -rf $(Build.ArtifactStagingDirectory)/lib/python3.8/test
    rm -rf $(Build.ArtifactStagingDirectory)/lib/python3.8/tkinter
  displayName: 'Clean up installation'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: python_ubuntu_1804


