
steps:
- checkout: self
  clean: true
  fetchDepth: 5

# Work around a known issue affecting Ubuntu VMs on Pipelines
- script: sudo setfacl -Rb /home/vsts
  displayName: 'Workaround ACL issue'

- script: sudo ./.azure-pipelines/posix-deps-apt.sh
  displayName: 'Install dependencies'

- script: ./configure  --enable-optimizations --enable-shared --with-pymalloc --prefix=$(Build.ArtifactStagingDirectory)
  displayName: 'Configure CPython (debug)'

- script: make -j4
  displayName: 'Build CPython'

- script: make pythoninfo
  displayName: 'Display build info'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: python_ubuntu_1804


