variables:
  - name: ldflags
    value: '-Wl,-rpath=\$$ORIGIN/../lib' 

steps:
- checkout: self
  clean: true
  fetchDepth: 5

# Work around a known issue affecting Ubuntu VMs on Pipelines
- script: sudo setfacl -Rb /home/vsts
  displayName: 'Workaround ACL issue'

- script: sudo ./.azure-pipelines/posix-deps-apt.sh
  displayName: 'Install dependencies'

- script: ./configure  --enable-shared --enable-optimizations --with-pymalloc --without-doc-strings --prefix=$(Build.ArtifactStagingDirectory)
  displayName: 'Configure CPython'

- template: ./unix-make-publish.yml
  parameters:
    artifactName: python_ubuntu_1804


