parameters:
  artifactName: python_unix

steps:
- script: make -j4
  displayName: 'Build CPython'

- script: make pythoninfo
  displayName: 'Display build info'

- script: make install
  displayName: 'Install into staging directory'

- template: ./clean-up-build.yml
  parameters:
    buildDir: $(Build.ArtifactStagingDirectory)

- script: |
    cd $(Build.ArtifactStagingDirectory)
    tar cvzf ${{ parameters.artifactName }}.tgz bin lib include
    rm -rfv bin lib include
  displayName: 'tar up to preserve links'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: ${{ parameters.artifactName }}


