steps:
- checkout: self
  clean: false
  fetchDepth: 5

- powershell: |
    # Relocate build outputs outside of source directory to make cleaning faster
    Write-Host '##vso[task.setvariable variable=Py_IntDir]$(Build.BinariesDirectory)\obj'
    # UNDONE: Do not build to a different directory because of broken tests
    Write-Host '##vso[task.setvariable variable=Py_OutDir]$(Build.BinariesDirectory)\bin'
    Write-Host '##vso[task.setvariable variable=EXTERNALS_DIR]$(Build.BinariesDirectory)\externals'
  displayName: Update build locations

- script: PCbuild\build.bat -v -e -p x64
  displayName: 'Build CPython'
  env:
    IncludeUwp: true

- script: python.bat -m test.pythoninfo
  displayName: 'Display build info'

- powershell: >
    Write-Host (
    '##vso[task.setvariable variable=LayoutCmd]&
    "python"
    "{1}\PC\layout"
    -vv
    --source "{1}"
    --build "{0}\bin\amd64"
    --arch "amd64"
    --temp "{0}\layout-temp"
    --include-cat "{0}\bin\amd64\python.cat"'
    -f ("$(Build.BinariesDirectory)", "$(Build.SourcesDirectory)")
    )

- powershell: |
    $d = (.\PCbuild\build.bat -V) | %{ if($_ -match '\s+(\w+):\s*(.+)\s*$') { @{$Matches[1] = $Matches[2];} }};
    Write-Host "##vso[task.setvariable variable=VersionText]$($d.PythonVersion)"
  displayName: 'Extract version numbers'

- powershell: >
    $(LayoutCmd)
    --copy "$(Build.ArtifactStagingDirectory)\layout"
    --zip "$(Build.ArtifactStagingDirectory)\embed\python-embed-win64.zip"
    --preset-embed
  displayName: 'Generate embeddable layout'

- task: PublishPipelineArtifact@0
  displayName: 'Publish Artifact: layout_embed_win64'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\layout'
    artifactName: layout_embed_win64

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: embed_win64'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\embed'
    ArtifactName: embed_win64