steps:
- checkout: self
  clean: false
  fetchDepth: 5

- powershell: |
    $d = (.\PCbuild\build.bat -V) | %{ if($_ -match '\s+(\w+):\s*(.+)\s*$') { @{$Matches[1] = $Matches[2];} }};
    Write-Host "##vso[task.setvariable variable=VersionText]$($d.PythonVersion)"
    Write-Host "##vso[task.setvariable variable=VersionNumber]$($d.PythonVersionNumber)"
    Write-Host "##vso[task.setvariable variable=VersionHex]$($d.PythonVersionHex)"
    Write-Host "##vso[task.setvariable variable=VersionUnique]$($d.PythonVersionUnique)"
  displayName: 'Extract version numbers'

- powershell: |
    # Relocate build outputs outside of source directory to make cleaning faster
    Write-Host '##vso[task.setvariable variable=Py_IntDir]$(Build.BinariesDirectory)\obj'
    # UNDONE: Do not build to a different directory because of broken tests
    Write-Host '##vso[task.setvariable variable=Py_OutDir]$(Build.BinariesDirectory)\bin'
    Write-Host '##vso[task.setvariable variable=EXTERNALS_DIR]$(Build.BinariesDirectory)\externals'
  displayName: Update build locations

- script: PCbuild\build.bat -v -e -p x64
  displayName: 'Build CPython'
  env:
    IncludeUwp: false

- powershell: |
    Write-Host '##vso[task.setvariable variable=Python]$(Build.BinariesDirectory)\bin\amd64\python.exe'
    Write-Host '##vso[task.setvariable variable=PYTHONHOME]$(Build.SourcesDirectory)'
  displayName: Set python path variables

- script: python.bat -m test.pythoninfo
  displayName: 'Display build info'

- powershell: |
    $env:SigningCertificate = $null
    python PC\layout -vv -b "$(Build.BinariesDirectory)\bin" -t "$(Build.BinariesDirectory)\catalog" --catalog "${env:CAT}.cdf" --preset-default --arch amd64
    makecat "${env:CAT}.cdf"
    del "${env:CAT}.cdf"
    if (-not (Test-Path "${env:CAT}.cat")) {
      throw "Failed to build catalog file"
    }
  displayName: 'Generate catalog'
  env:
    CAT: $(Build.BinariesDirectory)\bin\amd64\python
    PYTHON_HEXVERSION: $(VersionHex)

- powershell: >
    Write-Host (
    '##vso[task.setvariable variable=LayoutCmd]&
    "{0}\python.exe"
    "{1}\PC\layout"
    -vv
    --source "{1}"
    --build "{0}\bin\amd64"
    --arch "amd64"
    --temp "{0}\layout-temp"
    --include-cat "{0}\bin\amd64\python.cat"'
    -f ("$(Build.BinariesDirectory)", "$(Build.SourcesDirectory)")
    )
  displayName: 'Prepare layout command'

- powershell: >
    $(LayoutCmd)
    --copy "$(Build.ArtifactStagingDirectory)\layout"
    --zip "$(Build.ArtifactStagingDirectory)\embed\python-embed-win64.zip"
    --preset-embed
  displayName: 'Generate embeddable layout'

- task: PublishPipelineArtifact@0
  displayName: 'Publish Artifact: layout_embed_win64'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\layout'
    artifactName: layout_embed_win64

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: embed_win64'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\embed'
    ArtifactName: embed_win64